### ISSUE TITLE
Any demo site or screenshots of this CKAN feature extension?

### ISSUE THREAD

**Issue by ted-strauss-K1** [milicp/ckanext-lire#4]
I am interested in evaluating this CKAN extension and am looking for some example of it used on a live site, or screenshots of it's use in setup and front-end display. 
Are there any examples you can share?

**Comment by milicp** [comment]
Currently, I don't have screenshots and examples of it's use in setup 
and front-end display.

**Comment by ted-strauss-K1** [comment]
I have managed to get this extension installed and was able to make some screen captures. 

![image](https://cloud.githubusercontent.com/assets/930560/20728293/fbb4c71c-b64a-11e6-9177-814b7cd46bb0.png)

-------------------------------

![image](https://cloud.githubusercontent.com/assets/930560/20728320/258ca262-b64b-11e6-8fad-7fb6ddad24c7.png)

--------------------------------

![image](https://cloud.githubusercontent.com/assets/930560/20728367/61854706-b64b-11e6-98d6-dd84a8ab25cd.png)
